---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/favorite_spaces":
    get:
      summary: list favorite spaces
      tags:
        - FavoriteSpaces
      responses:
        "200":
          description: successful
    post:
      summary: create favorite space
      tags:
        - FavoriteSpaces
      parameters: []
      responses:
        "201":
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                space_id:
                  type: integer
              required:
                - space_id

  "/api/v1/users":
    get:
      summary: list users
      tags:
        - Users
      responses:
        "200":
          description: successful
    post:
      summary: create user
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        "201":
          description: created

  "/api/v1/users/{id}":
    get:
      summary: show user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful
    patch:
      summary: update user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: successful
    delete:
      summary: delete user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: no content
  "/api/v1/spaces/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show space
      tags:
        - Spaces
      responses:
        "200":
          description: successful
    patch:
      summary: update space
      tags:
        - Spaces
      parameters: []
      responses:
        "200":
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                building:
                  type: string
                capacity:
                  type: integer
    delete:
      summary: delete space
      tags:
        - Spaces
      responses:
        "204":
          description: no content
  "/api/v1/spaces/{id}/update_occupancy":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    post:
      summary: update occupancy
      tags:
        - Spaces
      parameters: []
      responses:
        "200":
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                occupancy:
                  type: integer
              required:
                - occupancy
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: www.example.com
