app = "roost-api"
primary_region = "yul"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "3000"
  RAILS_SERVE_STATIC_FILES = "true"
  BIND = "0.0.0.0"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[mounts]
  source = "rails_data"
  destination = "/data"

[deploy]
  release_command = "bin/rails db:migrate"

[processes]
  app = "bin/rails server"